/*
enum vtype {
        "vtype::SVjson",
        "vtype::SVjson5",
        "vtype::SVcstr",
        "vtype::SVvtab"
};
*/
interface rc {
	void rc();
	// error code
	readonly attribute long e;
	// result string
	[Const] readonly attribute DOMString v;
	// result string format enum as long
	readonly attribute long t;
	// name of t
	[Const] DOMString ts();
};

// attribute sequence<DOMString> stringArray;
interface ascjson {

 void ascjson();
 long config (DOMString vargv);

 [Const] rc libr_query (DOMString vargv);

// [Const] rc asc_compiler_option (DOMString vargv) ;

 [Const] rc libr_parsestring (DOMString vargv) ;

 [Const] rc librread (DOMString vargv) ;

 /// return is vtab separated with implicit subgroups 4 elements long
 [Const] rc libr_moduleinfo (DOMString vargv) ;

 [Const] rc libr_destroy_types (DOMString vargv) ;

 [Const] rc libr_hide_type (DOMString vargv) ;

 [Const] rc libr_unhide_type (DOMString vargv) ;

 [Const] rc libr_type_is_shown (DOMString vargv) ;

 [Const] rc libr_types_in_module (DOMString vargv) ;
/*
 [Const] rc libr_extract_type (DOMString vargv) ;

 [Const] rc qlfdid (DOMString vargv) ;

 [Const] rc bgetproc (DOMString vargv) ;

 [Const] rc brow_runmethod (DOMString vargv) ;

 [Const] rc brow_assign (DOMString vargv) ;

 [Const] rc qassgn3 (DOMString vargv) ;

 [Const] rc x__brow_iname (DOMString vargv) ;

 [Const] rc x__brow_isrelation (DOMString vargv) ;

 [Const] rc x__brow_ismodel (DOMString vargv) ;

 [Const] rc bgetrels (DOMString vargv) ;

 [Const] rc bgetrelspf (DOMString vargv) ;

 [Const] rc x__brow_relsforatom (DOMString vargv) ;

 [Const] rc x__brow_islogrel (DOMString vargv) ;

 [Const] rc bgetlogrels (DOMString vargv) ;

 [Const] rc bgetlogrelspf (DOMString vargv) ;

 [Const] rc x__brow_logrelsforatom (DOMString vargv) ;

 [Const] rc bgetcondrels (DOMString vargv) ;

 [Const] rc bgetcondlogrels (DOMString vargv) ;

 [Const] rc x__brow_iswhen (DOMString vargv) ;

 [Const] rc x__brow_isinstanceinwhen (DOMString vargv) ;

 [Const] rc bgetwhens (DOMString vargv) ;

 [Const] rc x__brow_whensforinstance (DOMString vargv) ;

 [Const] rc bwritependings (DOMString vargv) ;

 [Const] rc bnumpendings (DOMString vargv) ;

 [Const] rc count_names (DOMString vargv) ;

 [Const] rc aliases (DOMString vargv) ;

 [Const] rc isas (DOMString vargv) ;

 [Const] rc cliques (DOMString vargv) ;

 [Const] rc brow_child_list (DOMString vargv) ;

 [Const] rc bmerge (DOMString vargv) ;

 [Const] rc brefine (DOMString vargv) ;

 [Const] rc bmakealike (DOMString vargv) ;

 [Const] rc b_isplottable (DOMString vargv) ;

 [Const] rc b_prepplotfile (DOMString vargv) ;

 [Const] rc free_all_vars (DOMString vargv) ;

 [Const] rc Asc_SimBinTokenSetOptionsHC (DOMString vargv) ;

 [Const] rc sims (DOMString vargv) ;

 [Const] rc sim_instantiate (DOMString vargv) ;

 [Const] rc sim_unique (DOMString vargv) ;

 [Const] rc sim_reinstantiate (DOMString vargv) ;

 [Const] rc x__sims_copy (DOMString vargv) ;

 [Const] rc x__sims_proto (DOMString vargv) ;

 [Const] rc x__sims_saveinst (DOMString vargv) ;

 [Const] rc sim_destroy (DOMString vargv) ;

 [Const] rc simlistpending (DOMString vargv) ;
*/
 [Const] rc ddefine (DOMString vargv) ;

 [Const] rc ddiffdefine (DOMString vargv) ;

 [Const] rc disp (DOMString vargv) ;

 [Const] rc hier (DOMString vargv) ;

 [Const] rc file_by_type (DOMString vargv) ;

 [Const] rc dchild (DOMString vargv) ;

 [Const] rc drefines_me (DOMString vargv) ;

 [Const] rc drefines_meall (DOMString vargv) ;

 [Const] rc drefinement_tree (DOMString vargv) ;

 [Const] rc dgetparts (DOMString vargv) ;

 [Const] rc disroot_type (DOMString vargv) ;
/* userdata and probe bits
 [Const] rc x__probe (DOMString vargv) ;

 [Const] rc x__var_analyze (DOMString vargv) ;

 [Const] rc x__rel_analyze (DOMString vargv) ;

 [Const] rc x__userdata_init (DOMString vargv) ;

 [Const] rc x__userdata_create (DOMString vargv) ;

 [Const] rc x__userdata_destroy (DOMString vargv) ;

 [Const] rc x__userdata_save (DOMString vargv) ;

 [Const] rc x__userdata_restore (DOMString vargv) ;

 [Const] rc x__userdata_query (DOMString vargv) ;
*/
 [Const] rc x__userdata_print (DOMString vargv) ;

 [Const] rc get_model_children (DOMString vargv) ;

 [Const] rc slv_checksim (DOMString vargv) ;

 [Const] rc slv_checksys (DOMString vargv) ;

 [Const] rc slv_get_obj_list (DOMString vargv) ;

 [Const] rc slv_set_obj_by_num (DOMString vargv) ;

 [Const] rc slv_get_obj_num (DOMString vargv) ;

 [Const] rc slv_get_parms (DOMString vargv) ;

 [Const] rc set_slv_parms (DOMString vargv) ;

 [Const] rc set_slv_parmsnew (DOMString vargv) ;

 [Const] rc slv_get_parmsnew (DOMString vargv) ;

 [Const] rc slv_get_insttype (DOMString vargv) ;

 [Const] rc slv_get_cost_page (DOMString vargv) ;

 [Const] rc slv_get_stat_page (DOMString vargv) ;

 [Const] rc slv_get_objval (DOMString vargv) ;

 [Const] rc slv_get_instname (DOMString vargv) ;

 [Const] rc slv_get_pathname (DOMString vargv) ;

 [Const] rc slv_get_vr (DOMString vargv) ;

 [Const] rc slvdump (DOMString vargv) ;

 [Const] rc slv_presolve (DOMString vargv) ;

 [Const] rc slv_reanalyze (DOMString vargv) ;

 [Const] rc slv_check_and_reanalyze (DOMString vargv) ;

 [Const] rc slv_set_independent (DOMString vargv) ;

 [Const] rc slv_resolve (DOMString vargv) ;

 [Const] rc slv_solve (DOMString vargv) ;

 [Const] rc slv_iterate (DOMString vargv) ;

 [Const] rc slv_available (DOMString vargv) ;

 [Const] rc slv_number (DOMString vargv) ;

 [Const] rc slv_name (DOMString vargv) ;

 [Const] rc slv_linsol_names (DOMString vargv) ;

 [Const] rc slv_eligible_solver (DOMString vargv) ;

 [Const] rc slv_select_solver (DOMString vargv) ;

 [Const] rc slv_get_solver (DOMString vargv) ;

 [Const] rc slv_flush_solver (DOMString vargv) ;

 [Const] rc slv_import_qlfdid (DOMString vargv) ;

 [Const] rc slv_lnmget (DOMString vargv) ;

 [Const] rc slv_lnmset (DOMString vargv) ;

 [Const] rc slv_set_haltflag (DOMString vargv) ;

 [Const] rc slvhelp (DOMString vargv) ;

 [Const] rc slv_near_bounds (DOMString vargv) ;

 [Const] rc slv_far_from_nominals (DOMString vargv) ;

 [Const] rc slv_monitor (DOMString vargv) ;

 [Const] rc dbg_get_blk_of_var (DOMString vargv) ;

 [Const] rc dbg_get_blk_of_eqn (DOMString vargv) ;

 [Const] rc dbg_get_blk_coords (DOMString vargv) ;

 [Const] rc dbg_get_eqn_of_var (DOMString vargv) ;

 [Const] rc dbg_get_varpartition (DOMString vargv) ;

 [Const] rc dbg_get_eqnpartition (DOMString vargv) ;

 [Const] rc dbg_list_rels (DOMString vargv) ;

 [Const] rc dbg_list_vars (DOMString vargv) ;

 [Const] rc dbg_write_var (DOMString vargv) ;

 [Const] rc dbg_write_unattvar (DOMString vargv) ;

 [Const] rc brow_write_var (DOMString vargv) ;

 [Const] rc dbg_write_rel (DOMString vargv) ;

 [Const] rc brow_write_rel (DOMString vargv) ;

 [Const] rc dbg_write_obj (DOMString vargv) ;

 [Const] rc brow_write_obj (DOMString vargv) ;

 [Const] rc dbg_write_varattr (DOMString vargv) ;

 [Const] rc dbg_write_qlfattr (DOMString vargv) ;

 [Const] rc dbg_rel_included (DOMString vargv) ;

 [Const] rc dbg_var_fixed (DOMString vargv) ;

 [Const] rc dbg_get_incidence (DOMString vargv) ;

 [Const] rc dbg_get_order (DOMString vargv) ;

 [Const] rc dbg_write_incidence (DOMString vargv) ;

 [Const] rc dbg_find_eligible (DOMString vargv) ;

 [Const] rc brow_find_eligible (DOMString vargv) ;

 [Const] rc dbg_consistency_analysis (DOMString vargv) ;

 [Const] rc dbg_global_eligible (DOMString vargv) ;

 [Const] rc dbg_find_activerels (DOMString vargv) ;

 [Const] rc brow_find_activerels (DOMString vargv) ;

 [Const] rc dbg_struct_singular (DOMString vargv) ;

 [Const] rc dbg_num_block_singular (DOMString vargv) ;

 [Const] rc var_free2nom (DOMString vargv) ;

 [Const] rc var_nom2free (DOMString vargv) ;

 [Const] rc dbg_calc_relnoms (DOMString vargv) ;

 [Const] rc dbg_check_rels (DOMString vargv) ;

 [Const] rc dbg_write_slv0_xsys (DOMString vargv) ;

 [Const] rc dbg_write_slv0_sys (DOMString vargv) ;

 [Const] rc dbg_mtxwriteplot (DOMString vargv) ;

 [Const] rc dbg_calc_jacobian (DOMString vargv) ;

 [Const] rc dbghelp (DOMString vargv) ;

/* redo_integrator
 [Const] rc integrate_setup (DOMString vargv) ;

 [Const] rc integrate_cleanup (DOMString vargv) ;

 [Const] rc integrate_set_y_file (DOMString vargv) ;

 [Const] rc integrate_set_obs_file (DOMString vargv) ;

 [Const] rc integrate_logunits (DOMString vargv) ;

 [Const] rc integrate_logformat (DOMString vargv) ;

 [Const] rc integrate_get_samples (DOMString vargv) ;

 [Const] rc integrate_set_samples (DOMString vargv) ;

 [Const] rc integrate_able (DOMString vargv) ;
*/
/* mtx
 [Const] rc x__mtx_norms (DOMString vargv) ;

 [Const] rc mtx_gui_plot_incidence (DOMString vargv) ;

 [Const] rc mtxhelp (DOMString vargv) ;
*/

 [Const] rc u_destroy_units (DOMString vargv) ;

 [Const] rc u_setSIdef (DOMString vargv) ;

 [Const] rc u_getbasedef (DOMString vargv) ;

 [Const] rc u_dump (DOMString vargv) ;

 [Const] rc u_dims (DOMString vargv) ;

 [Const] rc u_dim_setverify (DOMString vargv) ;

 [Const] rc u_dim2num (DOMString vargv) ;

 [Const] rc u_num2dim (DOMString vargv) ;

 [Const] rc u_frombasedim (DOMString vargv) ;

 [Const] rc u_fromatomdim (DOMString vargv) ;

 [Const] rc u_getdimatoms (DOMString vargv) ;

 [Const] rc u_change_baseunit (DOMString vargv) ;

 [Const] rc u_getprec (DOMString vargv) ;

 [Const] rc u_setprec (DOMString vargv) ;

 [Const] rc u_get_atoms (DOMString vargv) ;

 [Const] rc u_get_units (DOMString vargv) ;

 [Const] rc u_set_user (DOMString vargv) ;

 [Const] rc u_get_user (DOMString vargv) ;

 [Const] rc u_get_list (DOMString vargv) ;

 [Const] rc u_clear_user (DOMString vargv) ;

 [Const] rc u_getval (DOMString vargv) ;

 [Const] rc u_browgetval (DOMString vargv) ;

 [Const] rc u_slvgetrelval (DOMString vargv) ;

 [Const] rc u_slvgetvarval (DOMString vargv) ;

 [Const] rc u_slvgetobjval (DOMString vargv) ;

 [Const] rc uhelp (DOMString vargv) ;

 [Const] rc srefine (DOMString vargv) ;

 [Const] rc smerge (DOMString vargv) ;
/*
 [Const] rc ascloadwin (DOMString vargv) ;
*/
 [Const] rc gnutext (DOMString vargv) ;

 [Const] rc help (DOMString vargv);

};
