 interface Annotation;
 interface AnnotationDatabase;
 interface Compiler;
 interface Dimensions;
 interface ExtMethod ;
 interface IncidencePoint;
 interface IncidenceMatrix;
 interface aw_Instance;
 interface InstanceInterfaceData;
 interface Integrator;
 interface IntegratorReporterCxx;
 interface IReporter ; // was ascxx_integratorreporter
 interface Library;
 interface Annotation_list ;
 interface Curve_list ;
 interface ExtMethod_list ;
 interface IncidencePoint_list ;
 interface aw_Instance_list ;
 interface Method_list ;
 interface Module_list ;
 interface Relation_list ;
 interface Solver_list ;
 interface Type_list ;
 interface UnitsM_list ;
 interface Variable_list ;
 interface Matrix;
 interface Method;
 interface Module;
 interface aw_Name;
 interface Registry;
 interface Reporter;
 interface Empty;
 interface aw_SetInt;
 interface aw_SetSymb;
 interface SingularityInfo;
 interface Solver;
 interface SolverHooks;
 interface SolverHooksManager;
 interface SolverParameter;
 interface SolverParameterIterator;
 interface SolverParameters;
 interface SolverReporter;
 interface SolverStatus;
 interface SymChar;
 interface Type;
 interface UnitsM;
 interface Value;
 interface Variable;
 interface Curve ;
 interface IntegratorReporterNull ;
 interface IntegratorReporterConsole ;
 interface Plot ;
 interface Relation ;
 interface Simulation ;
